Repository Lern-PFR/lern-web, pull requests merged in 2021-06, with the labels that each got.

#31 Implemented the signup page
  public/assets/svg/illustrations/mail_box.svg
  public/assets/svg/illustrations/sign_up.svg
  public/assets/svg/logo_black.svg
  src/api/usersApi.js
  src/components/auth/signup/SignUpForm.jsx
  src/components/auth/signup/index.js
  src/components/shared/styledElements/StyledSvg.jsx
  src/conf.js
  src/i18n/en.json
  src/i18n/fr.json
  src/lib/shared/formUtils.js
  src/lib/shared/inputValidation.js
  src/lib/shared/redirectionHelper.js
  src/pages/auth/PostSignupPage.jsx
  src/pages/auth/SignupPage.jsx
  src/pages/auth/index.js
  src/redux/actions/users.js
  src/redux/reducers/users.js
  src/routes/keys.js
  src/routes/routes.js
  src/theme/formStyles.js
  src/theme/pages/auth/postSignupPage.js
  src/theme/pages/auth/signUpPage.js
  tests/components/auth/SignUpForm.test.js
  tests/components/auth/__snapshots__/SignUpForm.test.js.snap
  tests/lib/shared/formUtils.test.js
  tests/lib/shared/inputValidation.test.js
  tests/lib/shared/redirectionHelper.test.js
  tests/pages/auth/PostSignupPage.test.js
  tests/pages/auth/__snapshots__/PostSignupPage.test.js.snap
  tests/redux/actions/users.test.js
  tests/redux/reducers/users.test.js
  tests/testUtils/forms/appendField.js
  tests/testUtils/forms/checkEmailPattern.js
  tests/testUtils/forms/checkRequired.js
  tests/testUtils/forms/containAtLeastOne.js
  tests/testUtils/forms/containInput.js
  tests/testUtils/forms/index.js
  tests/testUtils/forms/matchSnapshot.js
  tests/testUtils/forms/patterns.js
  tests/testUtils/forms/selector.js
  tests/testUtils/forms/setupForm.jsx
  tests/testUtils/forms/triggerValidationIndividually.js
Labels: Priority: Critical, Status: To validate, Type: Feature

#32 Implemented the signin page and fixed an issue about the detection of an authenticated user.
  public/assets/svg/illustrations/sign_in.svg
  src/api/authenticationApi.js
  src/components/auth/signin/SignInForm.jsx
  src/components/auth/signin/index.js
  src/components/shared/navigation/navbar/Navbar.jsx
  src/components/shared/styledElements/StyledSvg.jsx
  src/i18n/en.json
  src/i18n/fr.json
  src/pages/auth/SignInPage.jsx
  src/pages/auth/index.js
  src/redux/actions/users.js
  src/redux/reducers/users.js
  src/redux/selectors/users.js
  src/routes/components/RenderRoutes.jsx
  src/routes/components/RouteProvider.jsx
  src/routes/routes.js
  src/theme/buttonStyles.js
  src/theme/pages/auth/signInPage.js
  tests/api/authenticationApi.test.js
  tests/components/auth/SignInForm.test.js
  tests/components/auth/__snapshots__/SignInForm.test.js.snap
  tests/components/shared/navigation/navbar/Navbar.test.js
  tests/components/shared/navigation/navbar/__snapshots__/Navbar.test.js.snap
  tests/pages/auth/SignInPage.test.js
  tests/pages/auth/__snapshots__/SignInPage.test.js.snap
  tests/redux/actions/users.test.js
  tests/redux/reducers/users.test.js
  tests/redux/selectors/users.test.js
Labels: Priority: Critical, Status: To validate, Type: Feature

#30 Implemented reusable select component
  package.json
  src/components/App.jsx
  src/components/shared/form/CheckboxComponent.jsx
  src/components/shared/form/FieldsetComponent.jsx
  src/components/shared/form/InputComponent.jsx
  src/components/shared/form/LabeledInput.jsx
  src/components/shared/form/LabeledSelect.jsx
  src/components/shared/form/LegendComponent.jsx
  src/components/shared/form/RadioButtonComponent.jsx
  src/components/shared/form/SelectComponent.jsx
  src/components/shared/form/index.jsx
  src/theme/formStyles.js
  tests/components/auth/__snapshots__/SignUpForm.test.js.snap
  tests/components/notions/__snapshots__/QuestionForm.test.js.snap
  tests/components/shared/form/InputComponent.test.js
  tests/components/shared/form/LabeledCheckbox.test.js
  tests/components/shared/form/LabeledInput.test.js
  tests/components/shared/form/LabeledRadioButton.test.js
  tests/components/shared/form/LabeledSelect.test.js
  tests/components/shared/form/SelectComponent.test.js
  tests/components/shared/form/__snapshots__/InputComponent.test.js.snap
  tests/components/shared/form/__snapshots__/LabeledCheckbox.test.js.snap
  tests/components/shared/form/__snapshots__/LabeledInput.test.js.snap
  tests/components/shared/form/__snapshots__/LabeledRadioButton.test.js.snap
  tests/components/shared/form/__snapshots__/LabeledSelect.test.js.snap
  tests/components/shared/form/__snapshots__/SelectComponent.test.js.snap
  yarn.lock
Labels: Priority: Medium, Status: To validate, Type: Feature

#35 Handled the 409 HTTP error status on the signup page
  package.json
  src/i18n/en.json
  src/i18n/fr.json
  src/index.jsx
  src/lib/shared/http.js
  src/redux/actions/users.js
  tests/lib/shared/http.test.js
  tests/redux/actions/users.test.js
  yarn.lock
Labels: Priority: Low, Status: To validate, Type: Bug

#34 Implemented reusable textarea component
  src/components/App.jsx
  src/components/shared/form/LabeledTextArea.jsx
  src/components/shared/form/TextAreaComponent.jsx
  src/components/shared/form/index.jsx
  src/theme/formStyles.js
  tests/components/shared/form/LabeledRadioButton.test.js
  tests/components/shared/form/LabeledSelect.test.js
  tests/components/shared/form/LabeledTextArea.test.js
  tests/components/shared/form/TextAreaComponent.test.js
  tests/components/shared/form/__snapshots__/LabeledRadioButton.test.js.snap
  tests/components/shared/form/__snapshots__/LabeledSelect.test.js.snap
  tests/components/shared/form/__snapshots__/LabeledTextArea.test.js.snap
  tests/components/shared/form/__snapshots__/TextAreaComponent.test.js.snap
Labels: Priority: Medium, Status: To validate, Type: Feature

#37 Updated the subject details page's components to use the same field names as the API.
  src/components/subjects/ModuleList/ModuleList.jsx
  src/components/subjects/ModuleList/ModuleListItem.jsx
  src/redux/selectors/subjects.js
  tests/components/subjects/ModuleListItem.test.js
  tests/redux/selectors/subjects.test.js
Labels: Priority: Low, Status: Accepted, Type: Maintenance

#39 Updated the module details page components to use the same fields name as the API.
  src/components/modules/ConceptList.jsx
  src/components/modules/ConceptListItem.jsx
  src/components/modules/LessonListItem.jsx
  src/components/shared/buttons/DynamicLinkButtonComponent.jsx
  src/components/shared/buttons/index.jsx
  src/pages/modules/ModuleDetailsPage.jsx
  src/theme/pages/modules/moduleDetailsPage.js
  tests/components/modules/__snapshots__/LessonListItem.test.js.snap
  tests/components/modules/__snapshots__/NotionListItem.test.js.snap
Labels: Priority: Medium, Status: To validate, Type: Maintenance

#41 Implemented subject structure tutorial
  public/assets/svg/chevronRight.svg
  src/components/shared/form/LabelComponent.jsx
  src/i18n/en.json
  src/i18n/fr.json
  src/pages/subjects/SubjectStructurePage.jsx
  src/pages/subjects/index.js
  src/routes/keys.js
  src/routes/routes.js
  src/theme/pages/subjects/subjectStructurePage.js
  tests/components/concepts/__snapshots__/QuestionForm.test.js.snap
  tests/pages/subjects/SubjectStructurePage.test.js
  tests/pages/subjects/__snapshots__/SubjectStructurePage.test.js.snap
Labels: Priority: Medium, Status: To validate, Type: Feature

#42 Implemented the module creation page and fixed a dataflow issue.
  src/components/content/ModuleCreationForm.jsx
  src/components/content/NavigationSidebar.jsx
  src/components/content/SubjectModuleList.jsx
  src/components/content/SubjectModuleListItem.jsx
  src/components/content/index.js
  src/components/shared/layout/MainLayout.jsx
  src/i18n/en.json
  src/i18n/fr.json
  src/pages/modules/ModuleCreationPage.jsx
  src/pages/modules/index.js
  src/pages/subjects/SubjectEditionPage.jsx
  src/redux/actions/modules.js
  src/routes/keys.js
  src/routes/routes.js
  src/theme/buttonStyles.js
  tests/components/content/ModuleCreationForm.test.js
  tests/components/content/NavigationSidebar.test.js
  tests/components/content/SubjectModuleList.test.js
  tests/components/content/__snapshots__/ModuleCreationForm.test.js.snap
  tests/components/content/__snapshots__/NavigationSidebar.test.js.snap
  tests/components/content/__snapshots__/SubjectModuleList.test.js.snap
  tests/components/shared/buttons/__snapshots__/buttonElements.test.js.snap
  tests/pages/modules/ModuleCreationPage.test.js
  tests/pages/modules/__snapshots__/ModuleCreationPage.test.js.snap
  tests/redux/actions/modules.test.js
Labels: Priority: High, Status: To validate, Type: Feature

#44 Updated the concept details page to properly display data from the API.
  src/components/concepts/conceptDetailsPage/LessonContent.jsx
  src/components/concepts/conceptDetailsPage/Sidebar.jsx
  src/components/modules/ConceptList.jsx
  src/i18n/en.json
  src/i18n/fr.json
  src/pages/concepts/ConceptDetailsPage.jsx
  src/redux/actions/concepts.js
  src/redux/selectors/concepts.js
  src/redux/selectors/modules.js
  src/routes/routes.js
  tests/components/concepts/LessonContent.test.js
  tests/components/concepts/Sidebar.test.js
  tests/components/concepts/__snapshots__/Sidebar.test.js.snap
  tests/pages/concepts/ConceptDetailsPage.test.js
  tests/pages/concepts/__snapshots__/ConceptDetailsPage.test.js.snap
  tests/redux/actions/concepts.test.js
  tests/redux/selectors/concepts.test.js
  tests/redux/selectors/modules.test.js
Labels: Priority: High, Status: To validate, Type: Feature

#46 Renamed "courses" to "lessons" to match the API renaming.
  src/pages/modules/ModuleEditionPage.jsx
  src/redux/selectors/concepts.js
  src/redux/selectors/modules.js
  src/redux/selectors/subjects.js
  tests/pages/concepts/ConceptDetailsPage.test.js
  tests/redux/selectors/concepts.test.js
  tests/redux/selectors/modules.test.js
  tests/redux/selectors/subjects.test.js
Labels: Priority: Critical, Status: To validate, Type: Maintenance

#47 Fix signin behavior when login or password is incorrect
  public/favicon.ico
  public/favicon.png
  public/favicon_192.png
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  src/i18n/en.json
  src/i18n/fr.json
  src/lib/shared/http.js
  src/redux/actions/users.js
Labels: Priority: High, Status: To validate

#49 Removed the App component.
  src/components/App.jsx
  src/routes/routes.js
Labels: Priority: Low, Status: To validate, Type: Maintenance

#51 Implemented anonymous and authenticated user homepages
  public/assets/svg/illustrations/homepage_anon.svg
  public/assets/svg/illustrations/homepage_auth_no_active.svg
  src/api/progressionApi.js
  src/components/home/HomepageAnon.jsx
  src/components/home/HomepageAuth.jsx
  src/components/home/LatestCourses.jsx
  src/components/home/ProgressionListItem.jsx
  src/components/home/Sidebar.jsx
  src/components/home/SubjectListItem.jsx
  src/components/home/index.js
  src/components/shared/styledElements/StyledList.jsx
  src/i18n/en.json
  src/i18n/fr.json
  src/pages/home/Homepage.jsx
  src/pages/home/index.js
  src/redux/actions/progression.js
  src/redux/reducers/index.js
  src/redux/reducers/progression.js
  src/redux/selectors/progression.js
  src/routes/routes.js
  src/theme/pages/home/homepageAnon.js
  src/theme/pages/home/homepageAuth.js
  tests/components/concepts/__snapshots__/QuestionForm.test.js.snap
  tests/components/home/HomepageAnon.test.js
  tests/components/home/HomepageAuth.test.js
  tests/components/home/LatestCourses.test.js
  tests/components/home/ProgressionListItem.test.js
  tests/components/home/Sidebar.test.js
  tests/components/home/SubjectListItem.test.js
  tests/components/home/__snapshots__/HomepageAnon.test.js.snap
  tests/components/home/__snapshots__/HomepageAuth.test.js.snap
  tests/components/home/__snapshots__/LatestCourses.test.js.snap
  tests/components/home/__snapshots__/ProgressionListItem.test.js.snap
  tests/components/home/__snapshots__/Sidebar.test.js.snap
  tests/components/home/__snapshots__/SubjectListItem.test.js.snap
  tests/components/shared/styledElements/__snapshots__/StyledList.test.js.snap
  tests/pages/home/Homepage.test.js
  tests/pages/home/__snapshots__/Homepage.test.js.snap
  tests/redux/actions/progression.test.js
  tests/redux/reducers/progression.test.js
  tests/redux/selectors/progression.test.js
Labels: Priority: Critical, Status: Accepted, Type: Feature

#50 Updated the subject redux stack to properly update local data on subject edition.
  src/redux/actions/subjects.js
  src/redux/reducers/subjects.js
  tests/redux/actions/subjects.test.js
  tests/redux/reducers/subjects.test.js
Labels: Priority: Medium, Status: Accepted, Type: Bug

#52 Updated concept details page to allow users to answer questions and see their previous answers.
  src/api/resultsApi.js
  src/components/concepts/conceptDetailsPage/QuestionForm.jsx
  src/components/concepts/conceptDetailsPage/Sidebar.jsx
  src/components/shared/form/RadioButtonComponent.jsx
  src/pages/concepts/ConceptDetailsPage.jsx
  src/redux/actions/userAnswers.js
  src/redux/reducers/index.js
  src/redux/reducers/userAnswers.js
  src/redux/selectors/lessons.js
  src/redux/selectors/userAnswers.js
  src/theme/formStyles.js
  tests/components/concepts/QuestionForm.test.js
  tests/components/concepts/Sidebar.test.js
  tests/components/concepts/__snapshots__/QuestionForm.test.js.snap
  tests/components/concepts/__snapshots__/Sidebar.test.js.snap
  tests/components/shared/form/__snapshots__/RadioButtonComponent.test.js.snap
  tests/redux/actions/userAnswers.test.js
  tests/redux/reducers/userAnswers.test.js
  tests/redux/selectors/lessons.test.js
  tests/redux/selectors/userAnswers.test.js
Labels: Priority: Critical, Status: Accepted, Type: Feature

#53 Implemented the lesson creation page.
  src/components/content/LessonCreationForm.jsx
  src/components/content/NavigationSidebar.jsx
  src/components/content/index.js
  src/components/shared/layout/MainLayout.jsx
  src/i18n/en.json
  src/i18n/fr.json
  src/pages/lessons/LessonCreationPage.jsx
  src/pages/lessons/index.js
  src/redux/actions/lessons.js
  src/routes/keys.js
  src/routes/routes.js
  tests/components/content/LessonCreationForm.test.js
  tests/components/content/__snapshots__/LessonCreationForm.test.js.snap
  tests/components/modules/__snapshots__/LessonListItem.test.js.snap
  tests/pages/lessons/LessonCreationPage.test.js
  tests/pages/lessons/__snapshots__/LessonCreationPage.test.js.snap
  tests/redux/actions/lessons.test.js
Labels: Priority: High, Status: Accepted, Type: Feature

#54 Implemented the lesson edition page
  src/components/content/LessonEditionForm.jsx
  src/components/content/NavigationSidebar.jsx
  src/components/content/index.js
  src/components/shared/layout/MainLayout.jsx
  src/i18n/en.json
  src/i18n/fr.json
  src/pages/lessons/LessonEditionPage.jsx
  src/pages/lessons/index.js
  src/redux/actions/lessons.js
  src/redux/reducers/lessons.js
  src/redux/selectors/lessons.js
  src/redux/selectors/subjects.js
  src/routes/routes.js
  tests/components/content/LessonEditionForm.test.js
  tests/components/content/__snapshots__/LessonEditionForm.test.js.snap
  tests/pages/lessons/LessonEditionPage.test.js
  tests/pages/lessons/__snapshots__/LessonEditionPage.test.js.snap
  tests/redux/actions/lessons.test.js
  tests/redux/reducers/lessons.test.js
  tests/redux/selectors/lessons.test.js
  tests/redux/selectors/subjects.test.js
Labels: Priority: High, Status: Accepted, Type: Feature

#55 Correction de fautes d'orthographe et de grammaire
  src/i18n/fr.json
  src/lib/shared/i18n.js
Labels: Priority: High, Status: To validate, Type: Enhancement

#57 Add line breaks support and subject preview
  src/components/concepts/conceptDetailsPage/LessonContent.jsx
  src/components/content/SubjectEditionForm.jsx
  tests/components/concepts/__snapshots__/LessonContent.test.js.snap
  tests/components/content/SubjectEditionForm.test.js
  tests/components/content/__snapshots__/SubjectEditionForm.test.js.snap
Labels: Priority: Critical, Status: To validate, Type: Enhancement

#59 Add support for markdown in lessons content
  package.json
  src/components/concepts/conceptDetailsPage/LessonContent.jsx
  src/components/content/LessonCreationForm.jsx
  src/components/content/LessonEditionForm.jsx
  tests/components/concepts/__snapshots__/LessonContent.test.js.snap
  tests/components/content/LessonCreationForm.test.js
  tests/components/content/LessonEditionForm.test.js
  tests/components/content/__snapshots__/LessonCreationForm.test.js.snap
  tests/components/content/__snapshots__/LessonEditionForm.test.js.snap
  yarn.lock
Labels: Priority: Critical, Status: To validate, Type: Feature

#60 Fix lessons and module capitalize
  src/theme/pages/concepts/conceptDetailsPage.js
  src/theme/pages/modules/moduleDetailsPage.js
  tests/components/concepts/__snapshots__/LessonContent.test.js.snap
  tests/components/modules/__snapshots__/ConceptListItem.test.js.snap
  tests/components/modules/__snapshots__/LessonListItem.test.js.snap
Labels: Priority: Critical, Status: To validate, Type: Enhancement

#61 Fix lesson title hiding behind the navbar
  src/theme/pages/concepts/conceptDetailsPage.js
  tests/components/concepts/__snapshots__/LessonContent.test.js.snap
Labels: Priority: Critical, Status: To validate, Type: Enhancement
