Repository Lern-PFR/lern-web, pull requests merged in 2021-04, with the labels that each got.

#13 Implemented unit tests for the shared library methods.
  src/lib/shared/http.js
  src/lib/shared/session.js
  tests/lib/shared/http.test.js
  tests/lib/shared/localStorage.test.js
  tests/lib/shared/session.test.js
Labels: Priority: Critical, Status: Accepted, Type: Maintenance

#17 Implemented modules redux stack
  src/api/modulesApi.js
  src/redux/actions/modules.js
  src/redux/reducers/index.js
  src/redux/reducers/modules.js
  tests/redux/actions/modules.test.js
  tests/redux/reducers/modules.test.js
Labels: Priority: High, Status: Accepted, Type: Feature

#19 Implemented notions redux stack
  src/api/notionsApi.js
  src/redux/actions/notions.js
  src/redux/reducers/index.js
  src/redux/reducers/notions.js
  tests/redux/actions/notions.test.js
  tests/redux/reducers/notions.test.js
Labels: Priority: High, Status: Accepted, Type: Feature

#18 Add routing and i18n capabilities
  .env
  .eslintrc.js
  package.json
  src/api/authenticationApi.js
  src/components/App.jsx
  src/components/shared/buttons/index.jsx
  src/components/shared/layout/MainLayout.jsx
  src/components/shared/layout/StyledDiv.jsx
  src/components/shared/modal/Modal.jsx
  src/components/shared/modal/ModalFooter.jsx
  src/components/shared/modal/PromptModal.jsx
  src/components/shared/modal/index.js
  src/components/shared/modal/useModal.js
  src/components/shared/navigation/Link.jsx
  src/components/shared/navigation/index.js
  src/components/shared/typography/index.jsx
  src/i18n/en.json
  src/i18n/fr.json
  src/i18n/index.js
  src/index.js
  src/index.jsx
  src/lib/shared/environmentHelper.js
  src/lib/shared/http.js
  src/lib/shared/i18n.js
  src/pages/NotFound.jsx
  src/redux/actions/users.js
  src/routes/components/RenderRoutes.jsx
  src/routes/components/RouteProvider.jsx
  src/routes/components/RouterProvider.jsx
  src/routes/components/index.js
  src/routes/index.js
  src/routes/keys.js
  src/routes/routes.js
  src/theme/buttonStyles.js
  src/theme/modalStyles.js
  tests/api/authenticationApi.test.js
  tests/components/shared/layout/__snapshots__/StyledDiv.test.js.snap
  tests/components/shared/modal/Modal.test.js
  tests/components/shared/modal/ModalFooter.test.js
  tests/components/shared/modal/__snapshots__/Modal.test.js.snap
  tests/components/shared/modal/__snapshots__/ModalFooter.test.js.snap
  tests/components/shared/modal/useModal.test.js
  tests/i18n/i18n.test.js
  tests/lib/shared/environmentHelper.test.js
  tests/lib/shared/http.test.js
  tests/redux/actions/users.test.js
  tests/routes/components/Link.test.js
  tests/routes/components/RenderRoutes.test.js
  tests/routes/components/__snapshots__/Link.test.js.snap
  tests/routes/components/__snapshots__/RenderRoutes.test.js.snap
  tests/theme/__snapshots__/elevation.test.js.snap
  yarn.lock
Labels: Priority: Critical, Status: Accepted, Type: Feature

#21 Implemented reusable Checkbox and Label components
  Makefile
  src/components/App.jsx
  src/components/shared/form/CheckboxComponent.jsx
  src/components/shared/form/FieldsetComponent.jsx
  src/components/shared/form/LabelComponent.jsx
  src/components/shared/form/LabeledCheckbox.jsx
  src/components/shared/form/LegendComponent.jsx
  src/components/shared/form/index.jsx
  src/routes/routes.js
  src/theme/formStyles.js
  tests/components/shared/form/CheckboxComponent.test.js
  tests/components/shared/form/FieldsetComponent.test.js
  tests/components/shared/form/LabelComponent.test.js
  tests/components/shared/form/LabeledCheckbox.test.js
  tests/components/shared/form/LegendComponent.test.js
  tests/components/shared/form/__snapshots__/CheckboxComponent.test.js.snap
  tests/components/shared/form/__snapshots__/FieldsetComponent.test.js.snap
  tests/components/shared/form/__snapshots__/LabelComponent.test.js.snap
  tests/components/shared/form/__snapshots__/LabeledCheckbox.test.js.snap
  tests/components/shared/form/__snapshots__/LegendComponent.test.js.snap
Labels: Priority: Medium, Status: To validate, Type: Feature
