Repository Lern-PFR/lern-web, pull requests merged in 2021-03, with the labels that each got.

#4 Bumped react-scripts and react version to latest stables and update linter rules.
  .eslintcache
  .eslintrc.js
  package-lock.json
  package.json
  src/components/App.js
  src/components/App.jsx
  src/index.js
  src/redux/actions/users.js
  src/redux/enhancers/monitorReducers.js
  src/redux/middlewares/logger.js
  src/redux/reducers/index.js
  src/redux/reducers/users.js
  src/redux/store/configureStore.js
  tests/redux/actions/users.js
  tests/redux/reducers/users.js
Labels: Priority: High, Status: To validate, Type: Maintenance

#5 Implemented reusable typography elements along a dynamic text component which can be styled using js objects thanks to styled-system and styled-components.
  .eslintcache
  .eslintrc.js
  babel.config.json
  jest.config.js
  jsconfig.json
  package-lock.json
  package.json
  setupTests.js
  src/components/App.jsx
  src/components/shared/typography/DynamicTextComponent.jsx
  src/components/shared/typography/index.js
  src/theme/textStyles.js
  tests/components/shared/typography/DynamicTextComponent.test.js
  tests/components/shared/typography/__snapshots__/DynamicTextComponent.test.js.snap
  tests/components/shared/typography/__snapshots__/typographyElements.test.js.snap
  tests/components/shared/typography/typographyElements.test.js
Labels: Priority: Critical, Status: Accepted, Type: Enhancement

#9 Feature/config git attributes
  .eslintcache
  .gitattributes
  .gitignore
Labels: Priority: Critical, Status: Accepted, Type: Bug

#7 Added a MainLayout component to be used as parent to all pages of the application.
  public/baseStyle.css
  public/index.html
  src/components/App.jsx
  src/components/shared/layout/MainLayout.jsx
  src/components/shared/layout/StyledDiv.jsx
  src/components/shared/layout/index.js
  src/theme/layout.js
  tests/components/shared/layout/MainLayout.test.js
  tests/components/shared/layout/StyledDiv.test.js
  tests/components/shared/layout/__snapshots__/MainLayout.test.js.snap
  tests/components/shared/layout/__snapshots__/StyledDiv.test.js.snap
Labels: Priority: Medium, Status: Accepted, Type: Feature

#6 Implemented reusable button elements along a dynamic button component which can be styled using js objects thanks to styled-system and styled-components.
  package-lock.json
  package.json
  setupTests.js
  src/components/App.jsx
  src/components/shared/buttons/DynamicButtonComponent.jsx
  src/components/shared/buttons/index.jsx
  src/theme/buttonStyles.jsx
  src/theme/colors.jsx
  tests/components/shared/buttons/DynamicButtonComponent.test.js
  tests/components/shared/buttons/__snapshots__/DynamicButtonComponent.test.js.snap
  tests/components/shared/buttons/__snapshots__/buttonElements.test.js.snap
  tests/components/shared/buttons/buttonElements.test.js
Labels: Priority: Medium, Status: Accepted, Type: Enhancement

#10 Dockerized the application and added Makefile for convenience purposes. Switched from npm to yarn. Updated CI jobs to match new configuration.
  .dockerignore
  .env
  .github/workflows/linter.yml
  .github/workflows/test.yml
  Dockerfile
  Makefile
  docker-compose.yml
  package-lock.json
  yarn.lock
Labels: Priority: High, Status: Accepted, Type: Maintenance

#11 Implemented user redux stack
  package.json
  setupTests.js
  src/api/authenticationApi.js
  src/api/usersApi.js
  src/lib/shared/http.js
  src/lib/shared/localStorage.js
  src/lib/shared/session.js
  src/redux/actions/users.js
  src/redux/reducers/users.js
  tests/redux/actions/users.js
  tests/redux/actions/users.test.js
  tests/redux/reducers/users.js
  tests/redux/reducers/users.test.js
  yarn.lock
Labels: Priority: High, Status: Accepted, Type: Feature

#12 Feature/20 elevation shadows
  src/components/App.jsx
  src/theme/elevations.js
  tests/theme/__snapshots__/elevation.test.js.snap
  tests/theme/elevation.test.js
Labels: Priority: Medium, Status: Accepted, Type: Feature

#16 Renamed and fixed CI names
  .github/workflows/linter.yml
  .github/workflows/test.yml
Labels: Priority: Critical, Status: Pending, Type: Maintenance

#15 housekeeping : week 12
  yarn.lock
Labels: Status: Accepted, Type: Maintenance

#14 Implemented subject redux stack
  src/api/subjectsApi.js
  src/redux/actions/subjects.js
  src/redux/reducers/index.js
  src/redux/reducers/subjects.js
  tests/redux/actions/subjects.test.js
  tests/redux/reducers/subjects.test.js
Labels: Priority: High, Status: Accepted, Type: Feature
