Repository Lern-PFR/lern-web, pull requests merged in 2021-05, with the labels that each got.

#24 Implemented a redux stack for the lessons logic.
  src/api/lessonsApi.js
  src/redux/actions/lessons.js
  src/redux/reducers/index.js
  src/redux/reducers/lessons.js
  tests/redux/actions/lessons.test.js
  tests/redux/actions/notions.test.js
  tests/redux/reducers/lessons.test.js
Labels: Priority: High, Status: Accepted, Type: Feature

#27 Updated label component
  src/components/App.jsx
  src/components/shared/form/LabelComponent.jsx
  src/components/shared/form/LabeledCheckbox.jsx
  src/components/shared/form/LabeledRadioButton.jsx
  src/components/shared/form/index.jsx
  src/components/shared/typography/index.jsx
  src/theme/formStyles.js
  tests/components/shared/form/LabelComponent.test.js
  tests/components/shared/form/__snapshots__/FieldsetComponent.test.js.snap
  tests/components/shared/form/__snapshots__/LabelComponent.test.js.snap
  tests/components/shared/form/__snapshots__/LabeledCheckbox.test.js.snap
  tests/components/shared/form/__snapshots__/LabeledRadioButton.test.js.snap
  tests/components/shared/typography/typographyGetter.test.js
Labels: Priority: High, Status: To validate, Type: Enhancement

#25 Implemented reusable text input
  src/components/App.jsx
  src/components/shared/form/InputComponent.jsx
  src/components/shared/form/LabelComponent.jsx
  src/components/shared/form/LabeledInput.jsx
  src/components/shared/form/SubTextComponent.jsx
  src/components/shared/form/index.jsx
  src/theme/elevations.js
  src/theme/formStyles.js
  tests/components/shared/form/InputComponent.test.js
  tests/components/shared/form/LabeledInput.test.js
  tests/components/shared/form/__snapshots__/FieldsetComponent.test.js.snap
  tests/components/shared/form/__snapshots__/InputComponent.test.js.snap
  tests/components/shared/form/__snapshots__/LabelComponent.test.js.snap
  tests/components/shared/form/__snapshots__/LabeledCheckbox.test.js.snap
  tests/components/shared/form/__snapshots__/LabeledInput.test.js.snap
  tests/components/shared/form/__snapshots__/LabeledRadioButton.test.js.snap
  tests/theme/__snapshots__/elevation.test.js.snap
Labels: Priority: Medium, Status: Accepted, Type: Feature

#26 Implemented the notion details page
  package.json
  public/assets/svg/chevronLeft.svg
  src/components/App.jsx
  src/components/modules/LessonListItem.jsx
  src/components/modules/NotionList.jsx
  src/components/modules/NotionListItem.jsx
  src/components/notions/NotionDetailsPage/LessonContent.jsx
  src/components/notions/NotionDetailsPage/NotionContentNavigator.jsx
  src/components/notions/NotionDetailsPage/NotionContentNavigatorStepper.jsx
  src/components/notions/NotionDetailsPage/QuestionForm.jsx
  src/components/notions/NotionDetailsPage/Sidebar.jsx
  src/components/notions/NotionDetailsPage/index.js
  src/components/shared/buttons/DynamicButtonComponent.jsx
  src/components/shared/buttons/DynamicLinkButtonComponent.jsx
  src/components/shared/buttons/index.jsx
  src/components/shared/form/CheckboxComponent.jsx
  src/components/shared/form/LabelComponent.jsx
  src/components/shared/form/LabeledCheckbox.jsx
  src/components/shared/form/LabeledRadioButton.jsx
  src/components/shared/form/RadioButtonComponent.jsx
  src/components/shared/styledElements/StyledSvg.jsx
  src/components/shared/styledElements/index.js
  src/components/subjects/ModuleList/ModuleListItem.jsx
  src/i18n/en.json
  src/i18n/fr.json
  src/mockedData.js
  src/pages/modules/ModuleDetailsPage.jsx
  src/pages/notions/NotionDetailsPage.jsx
  src/pages/notions/index.js
  src/pages/subjects/SubjectDetailsPage.jsx
  src/routes/keys.js
  src/routes/routes.js
  src/theme/buttonStyles.js
  src/theme/colors.jsx
  src/theme/formStyles.js
  src/theme/pages/modules/moduleDetailsPage.js
  src/theme/pages/notions/notionDetailsPage.js
  src/theme/pages/subjects/subjectDetailsPage.js
  tests/components/modules/LessonListItem.test.js
  tests/components/modules/NotionListItem.test.js
  tests/components/modules/__snapshots__/LessonListItem.test.js.snap
  tests/components/modules/__snapshots__/NotionListItem.test.js.snap
  tests/components/notions/LessonContent.test.js
  tests/components/notions/NotionContentNavigator.test.js
  tests/components/notions/NotionContentNavigatorStepper.test.js
  tests/components/notions/QuestionForm.test.js
  tests/components/notions/Sidebar.test.js
  tests/components/notions/__snapshots__/LessonContent.test.js.snap
  tests/components/notions/__snapshots__/NotionContentNavigator.test.js.snap
  tests/components/notions/__snapshots__/NotionContentNavigatorStepper.test.js.snap
  tests/components/notions/__snapshots__/QuestionForm.test.js.snap
  tests/components/notions/__snapshots__/Sidebar.test.js.snap
  tests/components/shared/buttons/__snapshots__/buttonElements.test.js.snap
  tests/pages/modules/ModuleDetailsPage.test.js
  tests/pages/subjects/SubjectDetailsPage.test.js
  yarn.lock
Labels: Priority: Medium, Status: To validate, Type: Feature
